name: 💾 Core
description: Edit backends or the core of the sandwich machine
title: "[CORE] <title>"
labels: [enhancement]
assignees:
  - electron271
  - SoupHuman
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for this feature. (Also check closed issues)
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Information
    description: Information about the important edit
  validations:
    required: false
- type: textarea
  attributes:
    label: How will this improve our application
    description: Information of how this new feature will improve our project
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this issue! If you want to add some code, make a pull request [here](https://github.com/sandwich-machine/sandwich-machine/pulls) mentioning this issue.
  
- type: checkboxes
  attributes:
    label: Agreements
    description: Agreements for this issue
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
